#pragma once

#define CONTROLLER_SYMBOLIC_LINK   L"\\DosDevices\\vSerious"

#define IOCTL_VSERIOUS_SET_ACTIVE CTL_CODE(FILE_DEVICE_SERIAL_PORT, 0x800, METHOD_BUFFERED, FILE_WRITE_DATA)
#define IOCTL_VSERIOUS_GET_ACTIVE CTL_CODE(FILE_DEVICE_SERIAL_PORT, 0x801, METHOD_BUFFERED, FILE_READ_DATA)
#define IOCTL_VSERIOUS_SET_COM_NAME CTL_CODE(FILE_DEVICE_SERIAL_PORT, 0x802, METHOD_BUFFERED, FILE_WRITE_DATA)
#define IOCTL_VSERIOUS_GET_COM_NAME CTL_CODE(FILE_DEVICE_SERIAL_PORT, 0x803, METHOD_BUFFERED, FILE_READ_DATA)

#define COM_NAME_MAX_CCH 16

typedef struct _CONTROLLER_CONTEXT
{
    WDFDEVICE       Controller;

    BOOLEAN         Active;

    UNICODE_STRING  SymbolicLinkName;

    WCHAR SymbolicLinkBuffer[64];

    WCHAR ComName[COM_NAME_MAX_CCH];

} CONTROLLER_CONTEXT, * PCONTROLLER_CONTEXT;

WDF_DECLARE_CONTEXT_TYPE_WITH_NAME(CONTROLLER_CONTEXT, GetControllerContext);

typedef struct _VSERIOUS_PDO_IDENTIFICATION_DESCRIPTION
{
    WDF_CHILD_IDENTIFICATION_DESCRIPTION_HEADER Header;
    WCHAR ComName[COM_NAME_MAX_CCH];

} VSERIOUS_PDO_IDENTIFICATION_DESCRIPTION,
* PVSERIOUS_PDO_IDENTIFICATION_DESCRIPTION;

NTSTATUS
ControllerCreate(
    _In_  WDFDRIVER         Driver,
    _In_  PWDFDEVICE_INIT   DeviceInit,
    _Out_ PCONTROLLER_CONTEXT*  ControllerContext
);
